---
title: "01 16s Analysis Report"
output:
  pdf_document:
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
#library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
#renv::restore()
```



```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
#wd <- readLines("work_dir.txt")
#setwd(wd)
wd <- getwd()
print(wd)
ioi <- readLines(paste0("item_of_interest.csv"))
ioi<-as.character(ioi)

ioi_ord <- read.csv("order_item_of_interest.csv")
colnames(ioi_ord) <- ioi
ioi_ord <- as.list(ioi_ord)[[ioi]]

outdir_name <- "Figures"
if(!dir.exists(outdir_name)) {dir.create(outdir_name)}
outdir <- outdir_name
```

## 1 Species Distribution 

```{r import data into Microbiome Analyst Format, message=FALSE, warning=FALSE}
library(MicrobiomeAnalystR)
library(dplyr)
library(tidyr)


prepend <- "../../"
mbadir <- "microbiome_analyst_tmp"

if (!file.exists(mbadir)){
  dir.create(mbadir)
}


mbSet <- Init.mbSetObj()
mbSet<-SetModuleType(mbSet, "mdp")

options(bitmapType='cairo')
level = "Phylum"

#import ASV table from ampliseq analysis and write out properly fomatted one

new_table_file <- paste0(prepend,"qiime2/abundance_tables/feature-table.tsv")
new_table <- read.csv(new_table_file,sep='\t', skip=1)
new_table_df <- data.frame(new_table)
colnames(new_table_df)[1] <- "#NAME"
write.table(new_table_df,file = paste0(mbadir,"/ASV-tab.txt"),sep='\t',row.names = F)

mbSet <- Read16SAbundData(mbSet,paste0(mbadir,"/ASV-tab.txt"),"text",'SILVA','T')




#import taxonomy table from ampliseq analysis
new_tax_file <- paste0(prepend,"dada2/ASV_tax_species.tsv")
new_tax <- read.csv(new_tax_file,sep='\t')
new_tax_df <- data.frame(new_tax)
colnames(new_tax_df)[1] <- "#TAXONOMY"
new_tax_df <- new_tax_df %>%
  select(-c(confidence,sequence))
write.table(new_tax_df,file = paste0(mbadir,"/ASV_tax_species.txt"),sep='\t',row.names = F,quote = F)

mbSet <- Read16STaxaTable(mbSet, paste0(mbadir,"/ASV_tax_species.txt"))

#import rooted tree from ampliseq analysis 
new_tree_file <- paste0(prepend,"qiime2/phylogenetic_tree/tree.nwk")

mbSet <- ReadTreeFile(mbSet,new_tree_file)

#import metadata file 
new_metadata_file <- paste0(prepend,"all_days_sbm_cec_nf_treatment_metadata.tsv")
new_metadata <- read.csv(new_metadata_file,sep = '\t')
new_metadata_df <- data.frame(new_metadata)
colnames(new_metadata_df)[1]<-"#NAME"
write.table(new_metadata_df,file = paste0(mbadir,"/metadata.txt"),sep='\t',row.names = F,quote = F)

mbSet <- ReadSampleTable(mbSet,paste0(mbadir,"/metadata.txt"))

mbSet<-SanityCheckData(mbSet, "txt")

#TODO get this into the figure directory
mbSet<-PlotLibSizeView(mbSet, "norm_libsizes_0","png")

mbSet<-CreatePhyloseqObj(mbSet, "text","SILVA","F")

#Abundance filter (should have been handled by QIIME2)
#mbSet<-ApplyAbundanceFilter(mbSet, "prevalence", 4, 0.2);

#Varience filter (probably should be handled by QIIME2)
#mbSet<-ApplyVarianceFilter(mbSet, "iqr", 0.1)

# Data Normalization (maybe handled by QIIME2)
#mbSet<-PerformNormalization(mbSet, "none", "none", "none")

```

### 1.1 Relative Abundance of Top 10 Phyla

```{r stacked bar chart at Phylum level, echo=FALSE, fig.height=12, fig.width=18, message=FALSE, warning=FALSE}
library(MicrobiomeAnalystR)


# Merges taxa with count lower than 10 relative abundance
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_merge_relative_phylum","Phylum","condition", "none", "barnorm",10, "set3","sum",10, "bottom", "T", "png")

# Shows top 10 taxa (Will error out if less than 10) relative abundance
#TODO Create some code to check for top 10
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_subset_relative_phylum","Phylum","condition", "none", "barnorm",10, "set3","sum",10, "top", "T", "png")

# Merges taxa with counts lower than 10 absolute abundance
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_merge_absolute_phylum","Phylum","condition", "none", "barraw",10, "set3","sum",10, "bottom", "T", "png")

# Subsets top 10 taxa absolute
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_subset_absolute_phylum","Phylum","condition", "none", "barraw",10, "set3","sum",10, "top", "T", "png")
```

### 1.2 Relative Abundance of Top 10 Genera

```{r stacked bar chart at Genus level, echo=FALSE, fig.height=12, fig.width=18, message=FALSE, warning=FALSE}
library(MicrobiomeAnalystR)


# Merges taxa with count lower than 10 
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_13","Genus","condition", "none", "barnorm",10, "set3","sum",10, "bottom", "T", "png")

# Shows top 10 taxa (Will error out if less than 10)
#TODO Create some code to check for top 10
mbSet<-PlotTaxaAundanceBar(mbSet, "taxa_alpha_14","Genus","condition", "none", "barnorm",10, "set3","sum",10, "top", "T", "png")

```

### 1.3 Relative Abundance of Top 10 Species