---
title: "04 16s Analysis Report"
output:
  pdf_document:
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
#library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
#renv::restore()
```

```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
wd <- getwd()
ioi <- readLines("item_of_interest.csv")
ioi<-as.character(ioi)
```



## 4 Alpha Diversity Table

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
library(tidyverse)

obs <- read.table("results/qiime2/diversity/alpha_diversity/observed_features_vector/metadata.tsv", header = TRUE)
evenness <- read.table("results/qiime2/diversity/alpha_diversity/evenness_vector/metadata.tsv", header=TRUE)
shannon <- read.table("results/qiime2/diversity/alpha_diversity/shannon_vector/metadata.tsv", header = TRUE)
faith_pd <- read.table("results/qiime2/diversity/alpha_diversity/faith_pd_vector/metadata.tsv", header=TRUE)

obs <- data.frame(obs[c('id','observed_features')])
evenness <- data.frame(ace[c("id","pielou_evenness")])
shannon <- data.frame(shannon[c('id','shannon_entropy')])
faith_pd <- data.frame(faith_pd[c("id","faith_pd")])

alpha_summary <- Reduce(function(...) merge(..., by='id', all.x=TRUE), list(obs,evenness,shannon,faith_pd))
kable(alpha_summary) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

