---
title: "06b 16s Analysis Report"
output:
  pdf_document:
    df_print: kable
  html_document:
    df_print: kable
    smart: false
---

```{r init renv, message=FALSE, warning=FALSE, include=FALSE}
#library(renv)
#renv::isolate()
#renv::settings$snapshot.type("all")
#renv::restore()
```

```{r parse item of interest and make outdir for figures, echo=FALSE, message=FALSE, warning=FALSE}
#this may be required for each file
#item of interest, comes from bash and python script that orchestrates everything
wd <- getwd()
ioi <- readLines("item_of_interest.csv")
ioi<-as.character(ioi)

ioi_ord <- read.csv("order_item_of_interest.csv")
colnames(ioi_ord) <- ioi
ioi_ord <- as.list(ioi_ord)[[ioi]]

outdir_name <- "beta_diversity_ordination"
if(!dir.exists(outdir_name)) {dir.create(outdir_name)}
outdir <- outdir_name
```

```{r ampvis code from github so we dont need to query, echo=FALSE, message=FALSE, warning=FALSE}
phyloseq_to_ampvis2 <- function(physeq) {
  #check object for class
  if(!any(class(physeq) %in% "phyloseq"))
    stop("physeq object must be of class \"phyloseq\"", call. = FALSE)
  
  #ampvis2 requires taxonomy and abundance table, phyloseq checks for the latter
  if(is.null(physeq@tax_table))
    stop("No taxonomy found in the phyloseq object and is required for ampvis2", call. = FALSE)
  
  #OTUs must be in rows, not columns
  if(phyloseq::taxa_are_rows(physeq))
    abund <- as.data.frame(phyloseq::otu_table(physeq)@.Data)
  else
    abund <- as.data.frame(t(phyloseq::otu_table(physeq)@.Data))
  
  #tax_table is assumed to have OTUs in rows too
  tax <- phyloseq::tax_table(physeq)@.Data
  
  #merge by rownames (OTUs)
  otutable <- merge(
    abund,
    tax,
    by = 0,
    all.x = TRUE,
    all.y = FALSE,
    sort = FALSE
  )
  colnames(otutable)[1] <- "OTU"
  
  #extract sample_data (metadata)
  if(!is.null(physeq@sam_data)) {
    metadata <- data.frame(
      phyloseq::sample_data(physeq),
      row.names = phyloseq::sample_names(physeq), 
      stringsAsFactors = FALSE, 
      check.names = FALSE
    )
    
    #check if any columns match exactly with rownames
    #if none matched assume row names are sample identifiers
    samplesCol <- unlist(lapply(metadata, function(x) {
      identical(x, rownames(metadata))}))
    
    if(any(samplesCol)) {
      #error if a column matched and it's not the first
      if(!samplesCol[[1]])
        stop("Sample ID's must be in the first column in the sample metadata, please reorder", call. = FALSE)
    } else {
      #assume rownames are sample identifiers, merge at the end with name "SampleID"
      if(any(colnames(metadata) %in% "SampleID"))
        stop("A column in the sample metadata is already named \"SampleID\" but does not seem to contain sample ID's", call. = FALSE)
      metadata$SampleID <- rownames(metadata)
      
      #reorder columns so SampleID is the first
      metadata <- metadata[, c(which(colnames(metadata) %in% "SampleID"), 1:(ncol(metadata)-1L)), drop = FALSE]
    }
  } else
    metadata <- NULL
  
  #extract phylogenetic tree, assumed to be of class "phylo"
  if(!is.null(physeq@phy_tree)) {
    tree <- phyloseq::phy_tree(physeq)
  } else
    tree <- NULL
  
  #extract OTU DNA sequences, assumed to be of class "XStringSet"
  if(!is.null(physeq@refseq)) {
    #convert XStringSet to DNAbin using a temporary file (easiest)
    fastaTempFile <- tempfile(pattern = "ampvis2_", fileext = ".fa")
    Biostrings::writeXStringSet(physeq@refseq, filepath = fastaTempFile)
  } else
    fastaTempFile <- NULL
  
  #load as normally with amp_load
  ampvis2::amp_load(
    otutable = otutable,
    metadata = metadata,
    tree = tree,
    fasta = fastaTempFile
  )
}
```

## 6B Beta diversity Using NMDS 

### 6.1 Bray curtis ordination

```{r beta diversity plot of bray curtis measurement, echo=FALSE, message=FALSE, warning=FALSE}
library(qiime2R)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggConvexHull)
library(phyloseq)

table_dada2 <- "feature-table.qza"
rooted_tree <- "results/qiime2/phylogenetic_tree/rooted-tree.qza"
taxonomy_file <- "taxonomy.qza"
metadata_file <- "metadata.tsv"

cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file) 
cycle_1.ord <- ordinate(cycle_1, "NMDS", "bray")
bray_ord <- plot_ordination(cycle_1, cycle_1.ord, type="samples", color=ioi) + ggtitle(label= "NMDS ordination of Bray curtis", subtitle = paste0("Stress value = ", round(cycle_1.ord$stress,4)))
bray_ord_poly <- bray_ord + geom_polygon(aes_string(fill=ioi)) 

bray_ord

bray_ord_poly

ggsave("bray_curtis_nmds_ordination_polygon.png", plot=bray_ord_poly, path=outdir)
ggsave("bray_curtis_nmds_ordination.png", plot=bray_ord, path=outdir)
```




### 6.2 Jaccard ordination

```{r pcoa using Jaccard distance, echo=FALSE, message=FALSE, warning=FALSE}
library(qiime2R)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggConvexHull)
library(phyloseq)

cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file) 
cycle_1.ord <- ordinate(cycle_1, "NMDS", "jaccard")
jaccard_ord <- plot_ordination(cycle_1, cycle_1.ord, type="samples", color=ioi) + ggtitle(label= "NMDS ordination of Jaccard", subtitle = paste0("Stress value = ", round(cycle_1.ord$stress,4)))
jaccard_ord_poly <- jaccard_ord + geom_polygon(aes_string(fill=ioi)) 

jaccard_ord

jaccard_ord_poly

ggsave("jaccard_nmds_ordination_polygon.png", plot=jaccard_ord_poly, path=outdir)
ggsave("jaccard_nmds_ordination.png", plot=jaccard_ord, path=outdir)
```




### 6.3 Unweighted unifrac ordination

```{r unweighted unifrac pcoa ordination, echo=FALSE, message=FALSE, warning=FALSE}
library(qiime2R)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggConvexHull)
library(phyloseq)

cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file) 
cycle_1.ord <- ordinate(cycle_1, "NMDS", "unifrac")
u_unifrac_ord <- plot_ordination(cycle_1, cycle_1.ord, type="samples", color=ioi) + ggtitle(label= "NMDS ordination of Unweighted Unifrac", subtitle = paste0("Stress value = ", round(cycle_1.ord$stress,4)))
u_unifrac_ord_poly <- u_unifrac_ord + geom_polygon(aes_string(fill=ioi)) 

u_unifrac_ord

u_unifrac_ord_poly

ggsave("unweighted_unifrac_nmds_ordination_polygon.png", plot=u_unifrac_ord_poly, path=outdir)
ggsave("unweighted_unifrac_nmds_ordination.png", plot=u_unifrac_ord, path=outdir)
```




### 6.4 Weighted unifrac ordination

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(qiime2R)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggConvexHull)
library(phyloseq)

cycle_1 <- qza_to_phyloseq(table_dada2,rooted_tree,taxonomy_file,metadata_file) 
cycle_1.ord <- ordinate(cycle_1, "NMDS", "wunifrac")
w_unifrac_ord <- plot_ordination(cycle_1, cycle_1.ord, type="samples", color=ioi) + ggtitle(label= "NMDS ordination of Weighted Unifrac", subtitle = paste0("Stress value = ", round(cycle_1.ord$stress,4)))
w_unifrac_ord_poly <- w_unifrac_ord + geom_polygon(aes_string(fill=ioi)) 

w_unifrac_ord

w_unifrac_ord_poly

ggsave("weighted_unifrac_nmds_ordination_polygon.png", plot=w_unifrac_ord_poly, path=outdir)
ggsave("weighted_unifrac_nmds_ordination.png", plot=w_unifrac_ord, path=outdir)

```




